" enable vim default
"unlet! skip_defaults_vim
"source $VIMRUNTIME/defaults.vim

" load configure in vimrc.d
for f in split(glob("~/.vim/vimrc.d/*.vim"), '\n')
        exe "source" f
endfor

" vim-plug manager
" Following vim-plug tutorial
"
" Plugin download directory
call plug#begin("~/.vim/pluged")

" Declare list of plugin
" Plug '<PLUGIN_NAME>'
" For Github plugin     : username/project_id
" For Not Github plugin : full URL to plugin
" For local plugin      : file:///path-to-host
Plug 'Chiel92/vim-autoformat'                           " autoformat
Plug 'neoclide/coc.nvim', {'branch': 'release'}         " LSP frontend for autocompletion
Plug 'sheerun/vim-polyglot'                             " syntax highlight
Plug 'preservim/nerdtree'
"Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'bling/vim-bufferline'
Plug 'junegunn/fzf.vim'

" List end here. Plugin visible to vim after this call
call plug#end()
